variables:
  AMI_ID: "ami-073130f74f5ffb161"
  KEY_NAME: "deploy"
  SECURITY_GROUP: "sg-0b16f68678d01775c"
  INSTANCE_TYPE: "t3.micro"
  STORAGE: 100

 image: docker:24
services:
  - name: docker:24-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test_acceptation
  - release_image
  - deploy_staging
  - test_staging
  - deploy_prod
  - test_prod

# --- BUILD: build + save en artifact
docker-build:
  stage: build
  script:
    - echo "Build image..."
    - docker build -t static-website-example:ci .
    - echo "Save image to artifact..."
    - docker save static-website-example:ci > static-website-example.tar
  artifacts:
    paths:
      - static-website-example.tar
    expire_in: 1 hour

# --- TEST ACCEPTATION: load + run + curl
test acceptation:
  stage: test_acceptation
  script:
    - docker load < static-website-example.tar
    - docker run -d -p 8080:80 --name webapp static-website-example:ci
    - sleep 2
    - apk --no-cache add curl
    - curl -fsS "http://localhost:8080" >/tmp/page.html
    - grep -Ei "<html|<!doctype html" /tmp/page.html
    - docker rm -f webapp

# --- RELEASE: tag + push vers GitLab registry
release image:
  stage: release_image
  only:
    - master
  script:
    - docker load < static-website-example.tar

    # Tag vers ton registry (IMAGE_NAME vient des variables GitLab)
    - docker tag static-website-example:ci "${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}"
    - docker tag static-website-example:ci "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

# --- DEPLOY STAGING via SSH sur EC2 (ta variable HOSTNAME_DEPLOY_STAGING)
deploy staging:
  stage: deploy_staging
  only:
    - master
  environment:
    name: staging
    url: http://${HOSTNAME_DEPLOY_STAGING}
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa ${HOSTNAME_DEPLOY_STAGING} >> ~/.ssh/known_hosts

    - |
      ssh -t ${SSH_USER}@${HOSTNAME_DEPLOY_STAGING} "
        docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY} &&
        docker pull ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} &&
        docker rm -f webapp || true &&
        docker run -d -p 80:80 --name webapp ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
      "

# --- TEST STAGING
test staging:
  image: alpine:3.20
  stage: test_staging
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl -fsS "http://${HOSTNAME_DEPLOY_STAGING}" >/tmp/page.html
    - grep -Ei "<html|<!doctype html" /tmp/page.html

# --- DEPLOY PROD via SSH sur EC2
deploy prod:
  stage: deploy_prod
  only:
    - master
  environment:
    name: prod
    url: http://${HOSTNAME_DEPLOY_PROD}
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa ${HOSTNAME_DEPLOY_PROD} >> ~/.ssh/known_hosts

    - |
      ssh -t ${SSH_USER}@${HOSTNAME_DEPLOY_PROD} "
        docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY} &&
        docker pull ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} &&
        docker rm -f webapp || true &&
        docker run -d -p 80:80 --name webapp ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
      "

# --- TEST PROD
test prod:
  image: alpine:3.20
  stage: test_prod
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl -fsS "http://${HOSTNAME_DEPLOY_PROD}" >/tmp/page.html
    - grep -Ei "<html|<!doctype html" /tmp/page.html